baseURL = "https://oskar188salon.github.io/"
languageCode = "en-us"
title = "Oskar 188 Salon"
theme = "airspace-hugo"

[menu]

  [[menu.header]]
    weight = 1
    name = "Gallery"
    url = "#portfolio-work"

  [[menu.header]]
    weight = 2
    name = "Contact"
    url = "#contact"

  [[menu.header]]
    weight = 3
    name = "Location"
    url = "#location"

# The site's parameters
[params]

  # If you want to remove the copyright text you need a Themefisher license.
  # This license is offered with a 50% discount for all Hugo users.
  # For information see https://github.com/gohugoio/hugoThemes/issues/260

  dateFormat = "6 January 2006"

  home = "Home"

  [params.slider]
    enable = false
    title = "A digital marketing &amp; design agency"
    subtitle = "We love the Web and the work we do.<br/>We work closely with our clients to deliver the best possible solutions for their needs"

  [params.wrapper]
    enable = true
    title = "Hello"
    paragraph = "My name is Oskar and I am a professional hairstylist located in Burnaby, Vancouver. I have opened my new salon located at 4396 Imperial St. I am excited and look forward to provide professional solutions to make you look your very best! I am available for haircuts, shampoo, and styles every day of the week. Please call me and make an appointment for a pleasant and relaxing break in your day."

  [params.feature]
    enable = false
    title = "We believe in great ideas"
    content = ""
    [params.feature.button]
      caption = "View Works"
      url = "#"

  [params.call]
    enable = false
    title = "We design delightful digital experiences."
    paragraph = "Read more about what we do and our philosophy of design. Judge for yourself The work and results we’ve achieved for other clients, and meet our highly experienced Team who just love to design."

  [params.contact]
    enable = true
    title = "Stop by for the most trendy hairstyle in Vancouver"
    subtitle = ""
    [params.contact.box]
      title = "Contact"
      address = "4396 Imperial St, Burnaby, BC V5J 1A9"
      email = "Email: oskar188salon@gmail.com"
      phone = "Phone: +1 604 559 0306"
      insta = "Instagram: oskar188salon"
    [params.contact.gmaps]
      title = "Location"
